#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

# Use the provided interface, otherwise the device used for the default route.
if [[ -n $BLOCK_INSTANCE ]]; then
  IF=$BLOCK_INSTANCE
else
  IF=$(ip route | awk '/^default/ { print $5 ; exit }')
fi

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -f /sys/class/net/${IF}/operstate ]] && exit

#------------------------------------------------------------------------

if [[ "$(cat /sys/class/net/"$IF"/operstate)" = 'down' ]]; then
  echo -e "<span color='#60584E'><span size='10000'>\uf0ac</span> NO-CARRIER</span>"
  exit
fi

case $1 in
  -4)
    AF="inet" ;;
  -6)
    AF="inet6" ;;
  *)
    AF="inet6?" ;;
esac

# if no interface is found, use the first device with a global scope
IPADDR=$(ip addr show "$IF" | perl -n -e "/$AF ([^\/]+).* scope global/ && print \$1 and exit")

#QUALITY=$(grep $IF /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

#------------------------------------------------------------------------

# if [[ $QUALITY -lt 40 ]]; then
#   QUALITY="<span color='#FB4934'>[$QUALITY%]</span>"
# elif [[ $QUALITY -lt 60 ]]; then
#   QUALITY="<span color='#D79921'>[$QUALITY%]</span>"
# elif [[ $QUALITY -lt 80 ]]; then
#   QUALITY="<span color='#FABD2F'>[$QUALITY%]</span>"
# elif [[ $QUALITY -ge 80 ]]; then
#   QUALITY="<span color='#B8BB26'>[$QUALITY%]</span>"
# fi

# echo -e "<span size='10000'>\uf0ac</span> $IPADDR $QUALITY"
if [[ -z $IPADDR ]]; then
  echo -e "<span color='#60584E'><span size='10000'>\uf0ac</span> CAN'T GET IP</span>"
else
  echo -e "<span size='10000'>\uf0ac</span> $IPADDR"
fi
