#!/bin/bash

[[ $BLOCK_BUTTON -eq 1 ]] && xkblayout-state set +1

layout=$(xkblayout-state print "%s")

if [[ $layout = "us" ]]; then
  color="#4a4f4f"
  text="ENG"
elif [[ $layout = "ru" ]]; then
  color="#B5BD68"
  text="RUS"
else
  color="#FB4934"
  text="DVP"
fi

echo -e "<span color='$color'><span size='11000'>\uf11c</span> $text</span>"
