#!/usr/bin/env python

from sys import argv as sys_argv
from os import system as os_system
from datetime import datetime


if __name__ == '__main__':
    today_needs_to_be = sys_argv[1]
    message = sys_argv[2]

    today_is = 'odd' if int(datetime.today().strftime('%j')) % 2 else 'even'

    if today_is == today_needs_to_be:
        os_system('DISPLAY=:0 /usr/bin/notify-send "GRANNY REMINDER" "{}"'
                  .format(message))
