#!/usr/bin/env bash

action=$1

if [[ -z "$DISPLAY" ]] ; then
    read XUSER DISPLAY <<< $(ps au | grep -m1 xinit | awk '{print $1" "$15}')
    XAUTHORITY="/home/$XUSER/.Xauthority"
    export DISPLAY XAUTHORITY XUSER
fi

# Internal DELL laptop keyboard
internal="AT Translated Set 2 keyboard"
# External Leopold mechanical keyboard
external="HID Keyboard HID Keyboard"

debug () {
    echo "[$(date '+%d.%m.%Y %H:%M:%S')] $*" >> "/tmp/$(basename "$0").log"
}

# debug "action: $action, XUSER: $XUSER, XAUTHORITY: $XAUTHORITY, DISPLAY: $DISPLAY"

case "$action" in
    add)    xinput disable "$internal" ;;
    remove) xinput enable "$internal" ;;
    boot)   xinput list --name-only | grep -q "$external" && xinput disable "$internal" ;;
esac
