#!/usr/bin/env bash

action=$1

if [[ -z "$DISPLAY" ]] || [[ -z "$XUSER" ]]; then
    read XUSER DISPLAY <<< $(ps au | grep -m1 xinit | awk '{print $1" "$15}')
    XAUTHORITY="/home/$XUSER/.Xauthority"
    export DISPLAY XAUTHORITY XUSER
fi

debug () {
    echo "[$(date '+%d.%m.%Y %H:%M:%S')] $*" >> "/tmp/$(basename "$0").log"
}

mouse_name="A4Tech USB Optical Mouse"

run_imwheel () {
    if ! pgrep imwheel > /dev/null ; then
        if [[ $UID -eq 0 ]] ; then
            su - "$XUSER" -c "imwheel"
        else
            imwheel
        fi
    fi
}

kill_imwheel () {
    killall -u "$XUSER" -q imwheel
}

debug "action: $action, XUSER: $XUSER, XAUTHORITY: $XAUTHORITY, DISPLAY: $DISPLAY"

case "$action" in
    add)    run_imwheel ;;
    remove) kill_imwheel ;;
    boot)   xinput list --name-only | grep -q "$mouse_name" && run_imwheel || kill_imwheel ;;
esac
