#!/usr/bin/env python3

import trackers
import manager
from database import DBManager, DBError
from trackers import TrackerError


def get_tracker_instance(tracker_name, db_obj):
    return getattr(trackers, tracker_name.capitalize())(tracker_name, db_obj)


try:
    db = DBManager()
    for tracker_name, topics in db.get_topics():
        tracker = get_tracker_instance(tracker_name, db)
        for topic in topics:
            tracker.update(topic)

except TrackerError as message:
    manager.event_log('exception', message)
except DBError as message:
    manager.event_log('exception', message)
finally:
    # Commit changes to DB even if exeption occured
    if db.has_changes:
        db.topics.commit()
