#!/usr/bin/perl
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
# Copyright 2014 Andreas Guldstrand <andreas.guldstrand@gmail.com>
# Copyright 2014 Benjamin Chretien <chretien at lirmm dot fr>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;
use utf8;
use Getopt::Long;

binmode(STDOUT, ":utf8");

my $cpu;
my $fan;

open (SENSORS, "sensors -u dell_smm-virtual-0 |") or die;
while (<SENSORS>) {
    if (/^\s+fan1_input:\s+[\+]*([\-]*\d+)/) {
        $fan = $1;
    }
    if (/^\s+temp1_input:\s+[\+]*([\-]*\d+\.\d)/) {
        $cpu = $1;
        last;
    }
}
close(SENSORS);

$cpu or die 'Cannot find temperature';

if ($cpu >= 85) {
    print "%{F#CC6666} ";
} elsif ($cpu >= 70) {
    print "%{F#f0c674} ";
}else{
    print "%{F#4a4f4f}%{F-} ";
}

print $cpu."°C, ".$fan."rpm%{F-}";
exit 0;
